/****************************************************************************************************/
/*  Program Name:       2_4 Data cleaning for model build _Tapestry.sas                             */
/*                                                                                                  */
/*  Date Created:       July 29, 2022                                                               */
/*                                                                                                  */
/*  Created By:         Elle Haynes                                                                 */
/*                                                                                                  */
/*  Purpose:            Cleans the tapestry data for the KPIF EM OE23 Targeting Model.              */
/*                                                                                                  */
/*  Inputs:                                                                                         */
/*                                                                                                  */
/* -------------------------------------------------------------------------------------------------*/	
/*  Notes:              Targeting model will use 3 years of historical data from OE 2020-2022.      */
/* -------------------------------------------------------------------------------------------------*/
/*  Date Modified:                                                                                  */
/*  Modified by:                                                                                    */
/*  Description:                                                                                    */
/****************************************************************************************************/

/* -------------------------------------------------------------------------------------------------*/
/*  Libraries                                                                                       */
/* -------------------------------------------------------------------------------------------------*/

	* Output;
	%let output_files = /gpfsFS2/sasdata/nfs/ndc_grid/po_imca_digital/EHaynes/__Models/KPIF_EmailTargeting_2022;
	libname output "&output_files";

/* -------------------------------------------------------------------------------------------------*/
/*  Tapestry                                                                                        */
/* -------------------------------------------------------------------------------------------------*/

	data tapestry1;
		set output.t5_tapestry;

		/* Population, Households, and Density - 2020 */
		ESRI_FAM_POP_Pct = 100*(ESRI_FAM_POP/ESRI_TOT_POP);
/*		ESRI_TOT_POP*/
/*		ESRI_AVG_HH_SIZE*/
/*		ESRI_AVG_FAM_SIZE*/

		/* Population by Age - 2020 */
		ESRI_Pct_Tot_GEN_A = 100*(ESRI_GEN_A/ESRI_TOT_POP);
		ESRI_Pct_Tot_GEN_Z = 100*(ESRI_GEN_Z/ESRI_TOT_POP);
		ESRI_Pct_Tot_GEN_MIL = 100*(ESRI_GEN_MIL/ESRI_TOT_POP);
		ESRI_Pct_Tot_AGE_18_64 = 100*(ESRI_AGE_18_64/ESRI_TOT_POP);
		ESRI_Pct_Tot_AGE_20_24 = 100*(ESRI_AGE_20_24/ESRI_TOT_POP);
		ESRI_Pct_Tot_AGE_25_29 = 100*(ESRI_AGE_25_29/ESRI_TOT_POP);
		ESRI_Pct_Tot_AGE_30_34 = 100*(ESRI_AGE_30_34/ESRI_TOT_POP);
		ESRI_Pct_Tot_AGE_50_54 = 100*(ESRI_AGE_50_54/ESRI_TOT_POP);
		ESRI_Pct_Tot_AGE_55_60 = 100*(ESRI_AGE_55_60/ESRI_TOT_POP);
		ESRI_Pct_Tot_AGE_60_64 = 100*(ESRI_AGE_60_64/ESRI_TOT_POP);
		ESRI_Pct_AGE_20_24_W = 100*(ESRI_AGE_20_24_W/ESRI_AGE_20_24);
		ESRI_Pct_AGE_25_29_W = 100*(ESRI_AGE_25_29_W/ESRI_AGE_25_29);
		ESRI_Pct_AGE_30_34_W = 100*(ESRI_AGE_30_34_W/ESRI_AGE_30_34);
		ESRI_Pct_AGE_50_54_W = 100*(ESRI_AGE_50_54_W/ESRI_AGE_50_54);
		ESRI_Pct_AGE_55_60_W = 100*(ESRI_AGE_55_60_W/ESRI_AGE_55_60);
		ESRI_Pct_AGE_60_64_W = 100*(ESRI_AGE_60_64_W/ESRI_AGE_60_64);
		ESRI_Pct_AGE_20_24_B = 100*(ESRI_AGE_20_24_B/ESRI_AGE_20_24);
		ESRI_Pct_AGE_25_29_B = 100*(ESRI_AGE_25_29_B/ESRI_AGE_25_29);
		ESRI_Pct_AGE_30_34_B = 100*(ESRI_AGE_30_34_B/ESRI_AGE_30_34);
		ESRI_Pct_AGE_50_54_B = 100*(ESRI_AGE_50_54_B/ESRI_AGE_50_54);
		ESRI_Pct_AGE_55_60_B = 100*(ESRI_AGE_55_60_B/ESRI_AGE_55_60);
		ESRI_Pct_AGE_60_64_B = 100*(ESRI_AGE_60_64_B/ESRI_AGE_60_64);
		ESRI_Pct_AGE_20_24_A = 100*(ESRI_AGE_20_24_A/ESRI_AGE_20_24);
		ESRI_Pct_AGE_25_29_A = 100*(ESRI_AGE_25_29_A/ESRI_AGE_25_29);
		ESRI_Pct_AGE_30_34_A = 100*(ESRI_AGE_30_34_A/ESRI_AGE_30_34);
		ESRI_Pct_AGE_50_54_A = 100*(ESRI_AGE_50_54_A/ESRI_AGE_50_54);
		ESRI_Pct_AGE_55_60_A = 100*(ESRI_AGE_55_60_A/ESRI_AGE_55_60);
		ESRI_Pct_AGE_60_64_A = 100*(ESRI_AGE_60_64_A/ESRI_AGE_60_64);
		ESRI_Pct_AGE_20_24_PI = 100*(ESRI_AGE_20_24_PI/ESRI_AGE_20_24);
		ESRI_Pct_AGE_25_29_PI = 100*(ESRI_AGE_25_29_PI/ESRI_AGE_25_29);
		ESRI_Pct_AGE_30_34_PI = 100*(ESRI_AGE_30_34_PI/ESRI_AGE_30_34);
		ESRI_Pct_AGE_50_54_PI = 100*(ESRI_AGE_50_54_PI/ESRI_AGE_50_54);
		ESRI_Pct_AGE_55_60_PI = 100*(ESRI_AGE_55_60_PI/ESRI_AGE_55_60);
		ESRI_Pct_AGE_60_64_PI = 100*(ESRI_AGE_60_64_PI/ESRI_AGE_60_64);

		/* Race & Diversity - 2020 */
		ESRI_Pct_Tot_WHITE = 100*(ESRI_RACE_WHITE/ESRI_RACE_BASE);
		ESRI_Pct_Tot_BLACK = 100*(ESRI_RACE_BLACK/ESRI_RACE_BASE);
		ESRI_Pct_Tot_AM_IND = 100*(ESRI_RACE_AM_IND/ESRI_RACE_BASE);
		ESRI_Pct_Tot_ASIAN = 100*(ESRI_RACE_ASIAN/ESRI_RACE_BASE);
		ESRI_Pct_Tot_PAC_ISL = 100*(ESRI_RACE_PAC_ISL/ESRI_RACE_BASE);
		ESRI_Pct_Tot_HISPANIC = 100*(ESRI_RACE_HISPANIC/ESRI_RACE_BASE);
		ESRI_Pct_Tot_MINORITY = 100*(ESRI_RACE_MINORITY/ESRI_RACE_BASE);
/*		ESRI_DIVERSITY_INDEX*/

		ESRI_Pct_Tot_WHITE_FY = 100*(ESRI_RACE_WHITE_FY/ESRI_RACE_BASE_FY);
		ESRI_Pct_Tot_BLACK_FY = 100*(ESRI_RACE_BLACK_FY/ESRI_RACE_BASE_FY);
		ESRI_Pct_Tot_AM_IND_FY = 100*(ESRI_RACE_AM_IND_FY/ESRI_RACE_BASE_FY);
		ESRI_Pct_Tot_ASIAN_FY = 100*(ESRI_RACE_ASIAN_FY/ESRI_RACE_BASE_FY);
		ESRI_Pct_Tot_PAC_ISL_FY = 100*(ESRI_RACE_PAC_ISL_FY/ESRI_RACE_BASE_FY);
		ESRI_Pct_Tot_HISPANIC_FY = 100*(ESRI_RACE_HISPANIC_FY/ESRI_RACE_BASE_FY);
		ESRI_Pct_Tot_MINORITY_FY = 100*(ESRI_RACE_MINORITY_FY/ESRI_RACE_BASE_FY);
/*		ESRI_DIVERSITY_INDEX_FY*/
		ESRI_Pct_Chg_DIV_INDEX = 100*((ESRI_DIVERSITY_INDEX_FY/ESRI_DIVERSITY_INDEX)-1);

		/* Employment - 2020 */
/*		ESRI_UNEMPL_RATE*/
/*		ESRI_UNEMPL_RATE_16_24*/
/*		ESRI_UNEMPL_RATE_25_54*/
/*		ESRI_UNEMPL_RATE_55_64*/
		ESRI_Pct_IND_AGRICU = 100*(ESRI_INDUSTRY_AGRICU/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_MINING = 100*(ESRI_INDUSTRY_MINING/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_CONSTR = 100*(ESRI_INDUSTRY_CONSTR/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_MANUFA = 100*(ESRI_INDUSTRY_MANUFA/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_WHOLES = 100*(ESRI_INDUSTRY_WHOLES/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_RETAIL = 100*(ESRI_INDUSTRY_RETAIL/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_TRANSP = 100*(ESRI_INDUSTRY_TRANSP/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_UTILIT = 100*(ESRI_INDUSTRY_UTILIT/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_INFORM = 100*(ESRI_INDUSTRY_INFORM/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_FINANC = 100*(ESRI_INDUSTRY_FINANC/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_REAL = 100*(ESRI_INDUSTRY_REAL/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_PROFES = 100*(ESRI_INDUSTRY_PROFES/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_MGMT = 100*(ESRI_INDUSTRY_MGMT/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_WASTE = 100*(ESRI_INDUSTRY_WASTE/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_EDUCAT = 100*(ESRI_INDUSTRY_EDUCAT/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_HEALTH = 100*(ESRI_INDUSTRY_HEALTH/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_ENTERT = 100*(ESRI_INDUSTRY_ENTERT/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_FOOD = 100*(ESRI_INDUSTRY_FOOD/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_OTHER = 100*(ESRI_INDUSTRY_OTHER/ESRI_INDUSTRY_BASE);
		ESRI_Pct_IND_PUBLIC = 100*(ESRI_INDUSTRY_PUBLIC/ESRI_INDUSTRY_BASE);

		ESRI_Pct_OCCU_BIZ_MGMT = 100*(ESRI_OCCU_MGMT/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_BIZ_FINA = 100*(ESRI_OCCU_BIZ_FIN/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_COMP_MATH = 100*(ESRI_OCCU_COMP_MATH/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_ARCH_ENGI = 100*(ESRI_OCCU_ARCH_ENGI/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_LIFE_SCI = 100*(ESRI_OCCU_LIFE_SCI/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_SOC_SERV = 100*(ESRI_OCCU_SOC_SERVICE/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_LEGAL = 100*(ESRI_OCCU_LEGAL/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_EDUCATION = 100*(ESRI_OCCU_EDUCATION/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_HEALTH = 100*(ESRI_OCCU_HEALTH/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_HLTH_SUPP = 100*(ESRI_OCCU_HEALTH_SUPP/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_PROTECT = 100*(ESRI_OCCU_PROTECT/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_FOOD = 100*(ESRI_OCCU_FOOD/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_BLDG_MAIT = 100*(ESRI_OCCU_BLDG_MAINT/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_PERS_CARE = 100*(ESRI_OCCU_PERS_CARE/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_SALES = 100*(ESRI_OCCU_SALES/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_ADMIN = 100*(ESRI_OCCU_ADMIN/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_FARM = 100*(ESRI_OCCU_FARM/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_CONSTR = 100*(ESRI_OCCU_CONSTR/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_MAINT = 100*(ESRI_OCCU_MAINT/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_PROD = 100*(ESRI_OCCU_PROD/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_TRANSPORT = 100*(ESRI_OCCU_TRANSPORT/ESRI_OCCU_BASE);
		ESRI_Pct_OCCU_ENTERTAIN = 100*(ESRI_OCCU_ENTERTAIN/ESRI_OCCU_BASE);

		/* Education - 2020 */
		ESRI_Pct_EDUC_NO_HS = 100*((ESRI_EDUC_BASE-ESRI_EDUC_HS-ESRI_EDUC_GED-ESRI_EDUC_ASSO_DEG-ESRI_EDUC_BACH_DEG-ESRI_EDUC_GRAD_DEG)/ESRI_EDUC_BASE);
		ESRI_Pct_EDUC_HS = 100*(ESRI_EDUC_HS/ESRI_EDUC_BASE);
		ESRI_Pct_EDUC_GED = 100*(ESRI_EDUC_GED/ESRI_EDUC_BASE);
		ESRI_Pct_EDUC_ASSO_DEG = 100*(ESRI_EDUC_ASSO_DEG/ESRI_EDUC_BASE);
		ESRI_Pct_EDUC_BACH_DEG = 100*(ESRI_EDUC_BACH_DEG/ESRI_EDUC_BASE);
		ESRI_Pct_EDUC_GRAD_DEG = 100*(ESRI_EDUC_GRAD_DEG/ESRI_EDUC_BASE);

		/* Marital status - 2020 */
		ESRI_Pct_Tot_MARRIED = 100*(ESRI_MARRIED/ESRI_MARITAL_BASE);
		ESRI_Pct_Tot_WIDOWED = 100*(ESRI_WIDOWED/ESRI_MARITAL_BASE);
		ESRI_Pct_Tot_DIVORCED = 100*(ESRI_DIVORCED/ESRI_MARITAL_BASE);
		ESRI_Pct_Tot_NEVER_MARRIED = 100*(ESRI_NEVER_MARRIED/ESRI_MARITAL_BASE);

		/* Income - 2020 */
/*		ESRI_HHINCOME_MEDIAN*/
/*		ESRI_PER_CAPITA_INCOME*/
/*		ESRI_HHINCOME_AVG*/
/*		ESRI_WEALTH_INDEX*/
/*		ESRI_DISP_INCOME_MEDIAN*/
/*		ESRI_NET_WORTH_MEDIAN*/
		rename  ESRI_HHINCOME_AGE_15_24 = ESRI_MED_HHINC_AGE_15_24
				ESRI_HHINCOME_AGE_25_34 = ESRI_MED_HHINC_AGE_25_34
				ESRI_HHINCOME_AGE_35_44 = ESRI_MED_HHINC_AGE_35_44
				ESRI_HHINCOME_AGE_45_54 = ESRI_MED_HHINC_AGE_45_54
				;
		ESRI_Pct_Tot_HHINC_0_14k = 100*(ESRI_HHINCOME_0_14k/ESRI_HHINCOME_BASE);
		ESRI_Pct_Tot_HHINC_15_24k = 100*(ESRI_HHINCOME_15_24k/ESRI_HHINCOME_BASE);
		ESRI_Pct_Tot_HHINC_25_34k = 100*(ESRI_HHINCOME_25_34k/ESRI_HHINCOME_BASE);
		ESRI_Pct_Tot_HHINC_35_49k = 100*(ESRI_HHINCOME_35_49k/ESRI_HHINCOME_BASE);
		ESRI_Pct_Tot_HHINC_50_74k = 100*(ESRI_HHINCOME_50_74k/ESRI_HHINCOME_BASE);
		ESRI_Pct_Tot_HHINC_75_99k = 100*(ESRI_HHINCOME_75_99k/ESRI_HHINCOME_BASE);

		/* Income - 2025 */
/*		ESRI_HHINCOME_MEDIAN_FY*/
		ESRI_Pct_Chg_HHINC_MED = 100*((ESRI_HHINCOME_MEDIAN_FY/ESRI_HHINCOME_MEDIAN)-1);
		ESRI_Pct_Tot_HHINC_0_14k_FY = 100*(ESRI_HHINCOME_0_14k_FY/ESRI_HHINCOME_BASE_FY);
		ESRI_Pct_Tot_HHINC_15_24k_FY = 100*(ESRI_HHINCOME_15_24k_FY/ESRI_HHINCOME_BASE_FY);
		ESRI_Pct_Tot_HHINC_25_34k_FY = 100*(ESRI_HHINCOME_25_34k_FY/ESRI_HHINCOME_BASE_FY);
		ESRI_Pct_Tot_HHINC_35_49k_FY = 100*(ESRI_HHINCOME_35_49k_FY/ESRI_HHINCOME_BASE_FY);
		ESRI_Pct_Tot_HHINC_50_74k_FY = 100*(ESRI_HHINCOME_50_74k_FY/ESRI_HHINCOME_BASE_FY);
		ESRI_Pct_Tot_HHINC_75_99k_FY = 100*(ESRI_HHINCOME_75_99k_FY/ESRI_HHINCOME_BASE_FY);

		/* Housing & Affordability - 2020 */
/*		ESRI_PCT_INCOME_MORTG*/
/*		ESRI_HOUSING_AFFORD_INDEX*/
/*		ESRI_HOME_VALUE_MEDIAN*/
/*		ESRI_HOME_VALUE_MEDIAN_FY*/
		ESRI_Pct_Chg_HOME_VAL_MED = 100*((ESRI_HOME_VALUE_MEDIAN_FY/ESRI_HOME_VALUE_MEDIAN)-1);
		ESRI_HOUSING_PerPerson = ESRI_HOUSING_UNITS/ESRI_TOT_POP;
		ESRI_Pct_HOUSING_OWNER = 100*(ESRI_HOUSING_OWNER/ESRI_HOUSING_UNITS);
		ESRI_Pct_HOUSING_RENTER = 100*(ESRI_HOUSING_RENTER/ESRI_HOUSING_UNITS);
		ESRI_Pct_HOUSING_VACANT = 100*(ESRI_HOUSING_VACANT/ESRI_HOUSING_UNITS);

		/* Tapestry segments */
/*		TAPESTRY_SEGMENT*/
/*		TAPESTRY_LIFESTYLE*/
/*		TAPESTRY_URBAN*/

		drop ESRI_HH_POP	ESRI_FAM_POP	ESRI_TOT_HH		ESR_FAM_HH
			 ESRI_GEN_A		ESRI_GEN_Z		ESRI_GEN_MIL
			 ESRI_AGE_18_64	ESRI_AGE_20_24	ESRI_AGE_25_29	ESRI_AGE_30_34
			 ESRI_AGE_50_54	ESRI_AGE_55_60	ESRI_AGE_60_64
			 ESRI_AGE_20_24_W				ESRI_AGE_25_29_W
			 ESRI_AGE_30_34_W				ESRI_AGE_50_54_W
			 ESRI_AGE_55_60_W				ESRI_AGE_60_64_W
			 ESRI_AGE_20_24_B				ESRI_AGE_25_29_B
			 ESRI_AGE_30_34_B				ESRI_AGE_50_54_B
			 ESRI_AGE_55_60_B				ESRI_AGE_60_64_B
			 ESRI_AGE_20_24_A				ESRI_AGE_25_29_A
			 ESRI_AGE_30_34_A				ESRI_AGE_50_54_A
			 ESRI_AGE_55_60_A				ESRI_AGE_60_64_A
			 ESRI_AGE_20_24_PI				ESRI_AGE_25_29_PI
			 ESRI_AGE_30_34_PI				ESRI_AGE_50_54_PI
			 ESRI_AGE_55_60_PI				ESRI_AGE_60_64_PI
			 ESRI_RACE_BASE					ESRI_RACE_WHITE	
			 ESRI_RACE_BLACK				ESRI_RACE_AM_IND
			 ESRI_RACE_ASIAN				ESRI_RACE_PAC_ISL
			 ESRI_RACE_HISPANIC				ESRI_RACE_MINORITY
			 ESRI_RACE_BASE_FY				ESRI_RACE_WHITE_FY
		 	 ESRI_RACE_BLACK_FY				ESRI_RACE_AM_IND_FY
			 ESRI_RACE_ASIAN_FY				ESRI_RACE_PAC_ISL_FY
			 ESRI_RACE_HISPANIC_FY			ESRI_RACE_MINORITY_FY
			 ESRI_INDUSTRY_BASE				ESRI_INDUSTRY_AGRICU
			 ESRI_INDUSTRY_MINING			ESRI_INDUSTRY_CONSTR
			 ESRI_INDUSTRY_MANUFA			ESRI_INDUSTRY_WHOLES
			 ESRI_INDUSTRY_RETAIL			ESRI_INDUSTRY_TRANSP
			 ESRI_INDUSTRY_UTILIT			ESRI_INDUSTRY_INFORM
			 ESRI_INDUSTRY_FINANC			ESRI_INDUSTRY_REAL
			 ESRI_INDUSTRY_PROFES			ESRI_INDUSTRY_MGMT
			 ESRI_INDUSTRY_WASTE			ESRI_INDUSTRY_EDUCAT
			 ESRI_INDUSTRY_HEALTH			ESRI_INDUSTRY_ENTERT
			 ESRI_INDUSTRY_FOOD				ESRI_INDUSTRY_OTHER
			 ESRI_INDUSTRY_PUBLIC
			 ESRI_OCCU_BASE					ESRI_OCCU_BIZ_FIN
			 ESRI_OCCU_COMP_MATH			ESRI_OCCU_ARCH_ENGI
			 ESRI_OCCU_LIFE_SCI				ESRI_OCCU_SOC_SERVICE
			 ESRI_OCCU_LEGAL				ESRI_OCCU_EDUCATION
			 ESRI_OCCU_HEALTH				ESRI_OCCU_PROTECT
			 ESRI_OCCU_FOOD					ESRI_OCCU_BLDG_MAINT
			 ESRI_OCCU_PERS_CARE			ESRI_OCCU_SALES
			 ESRI_OCCU_ADMIN				ESRI_OCCU_FARM
			 ESRI_OCCU_CONSTR				ESRI_OCCU_MAINT
			 ESRI_OCCU_PROD					ESRI_OCCU_TRANSPORT
			 ESRI_OCCU_ENTERTAIN			ESRI_OCCU_MGMT
			 ESRI_OCCU_HEALTH_SUPP
			 ESRI_EDUC_BASE					ESRI_EDUC_NO_HS	
			 ESRI_EDUC_HS					ESRI_EDUC_GED
			 ESRI_EDUC_ASSO_DEG				ESRI_EDUC_BACH_DEG
			 ESRI_EDUC_GRAD_DEG
			 ESRI_MARITAL_BASE				ESRI_MARRIED
			 ESRI_WIDOWED					ESRI_DIVORCED
			 ESRI_NEVER_MARRIED
			 ESRI_HHINCOME_BASE				ESRI_HHINCOME_0_14k
			 ESRI_HHINCOME_15_24k		    ESRI_HHINCOME_25_34k
			 ESRI_HHINCOME_35_49k			ESRI_HHINCOME_50_74k
			 ESRI_HHINCOME_75_99k
			 ESRI_HHINCOME_BASE_FY			ESRI_HHINCOME_0_14k_FY
			 ESRI_HHINCOME_15_24k_FY		ESRI_HHINCOME_25_34k_FY
			 ESRI_HHINCOME_35_49k_FY		ESRI_HHINCOME_50_74k_FY
			 ESRI_HHINCOME_75_99k_FY
			 ESRI_HOUSING_UNITS				ESRI_HOUSING_OWNER
			 ESRI_HOUSING_RENTER			ESRI_HOUSING_VACANT
			 GEOCODE 						ESRI_TOT_POP
			;
		run;

	proc sql;
	create table output.t11_Rollup_Tapestry as
	select distinct
		x.AGLTY_INDIV_ID
	,	x.OE_Season
	,	y.*
	from output.t9_rollup_treatment x
	left join tapestry1 y
		on x.AGLTY_INDIV_ID=y.AGLTY_INDIV_ID;
	quit;

	* Export;
	proc export 
		data=output.t11_Rollup_Tapestry
		outfile="&output_files/T11_Rollup_Tapestry.csv"
		dbms=CSV replace;
	run;			
