/****************************************************************************************************/
/*  Program Name:       SQL Server_ TENURE_CODE OE2020.sql                                          */
/*                                                                                                  */
/*  Date Created:       July 8, 2022                                                                */
/*                                                                                                  */
/*  Created By:         Elle Haynes                                                                 */
/*                                                                                                  */
/*  Purpose:            Calculates tenure (prior to OE2020) for the KPIF EM OE 2023 Targeting model.*/
/*                                                                                                  */
/*  Inputs:                                                                                         */
/*                                                                                                  */
/* -------------------------------------------------------------------------------------------------*/
/*  Notes:              Targeting model will use 3 years of historical data from OE 2020-2022.      */
/* -------------------------------------------------------------------------------------------------*/
/*  Date Modified:      July 14, 2022                                                               */
/*  Modified by:        Elle Haynes                                                                 */
/*  Description:        Re-pulled data because Member was updated July 10, 2022                     */
/****************************************************************************************************/

/* Connected to server 3778 */

--INPUT MBR HISTORY FILE
SELECT DISTINCT
	AGLTY_INDIV_ID
,	MIN(PROMO_START_DT) AS FIRST_PROMOTION_OF_SEASON
INTO #OE20
FROM WS_EHAYNES.dbo.KPIF_EM_22_Targeting_AgilityIDs
WHERE YEAR(PROMO_START_DT)=2019 -- ONLY OE2020
GROUP BY 
	AGLTY_INDIV_ID

SELECT DISTINCT
	x.AGLTY_INDIV_ID
,	x.FIRST_PROMOTION_OF_SEASON
,	m.ELGB_START_DT
,	m.ELGB_END_DT
INTO #DATA
FROM #OE20 x
LEFT JOIN p4685.MARS.dbo.MEMBER m 
	ON x.AGLTY_INDIV_ID=m.AGLTY_INDIV_ID

DELETE FROM #DATA WHERE ELGB_START_DT = CONVERT(DATE,'1900-01-01') AND ELGB_END_DT = CONVERT(DATE,'1900-01-01')
DELETE FROM #DATA WHERE ELGB_START_DT >= ELGB_END_DT
DELETE FROM #DATA WHERE ELGB_START_DT > FIRST_PROMOTION_OF_SEASON

SELECT DISTINCT A.AGLTY_INDIV_ID, A.ELGB_START_DT, 
	(SELECT CASE WHEN ELGB_END_DT > FIRST_PROMOTION_OF_SEASON THEN FIRST_PROMOTION_OF_SEASON ELSE ELGB_END_DT END) AS ELGB_END_DT
	INTO #TEMP1
	FROM #DATA A --FILE INPUT]
--
CREATE TABLE #TEMPDATES (AGLTY_INDIV_ID NVARCHAR(20), 
T01_START DATETIME, T01_END DATETIME, 
T02_START DATETIME, T02_END DATETIME, 
T03_START DATETIME, T03_END DATETIME,
T04_START DATETIME, T04_END DATETIME,
T05_START DATETIME, T05_END DATETIME,
T06_START DATETIME, T06_END DATETIME,
T07_START DATETIME, T07_END DATETIME,
T08_START DATETIME, T08_END DATETIME,
T09_START DATETIME, T09_END DATETIME,
T10_START DATETIME, T10_END DATETIME,
T11_START DATETIME, T11_END DATETIME,
T12_START DATETIME, T12_END DATETIME,
T13_START DATETIME, T13_END DATETIME,
T14_START DATETIME, T14_END DATETIME,
T15_START DATETIME, T15_END DATETIME,
T16_START DATETIME, T16_END DATETIME,
T17_START DATETIME, T17_END DATETIME,
T18_START DATETIME, T18_END DATETIME,
T19_START DATETIME, T19_END DATETIME,
T20_START DATETIME, T20_END DATETIME
)
	INSERT INTO #TEMPDATES (AGLTY_INDIV_ID)
	SELECT DISTINCT AGLTY_INDIV_ID FROM #TEMP1

	UPDATE #TEMPDATES SET T01_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T01_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T01_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)
	
	UPDATE #TEMPDATES SET T02_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T02_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T02_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)
	
	UPDATE #TEMPDATES SET T03_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T03_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T03_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)
	
	UPDATE #TEMPDATES SET T04_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T04_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T04_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)
		
	UPDATE #TEMPDATES SET T05_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T05_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T05_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)
		
	UPDATE #TEMPDATES SET T06_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T06_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T06_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)
		
	UPDATE #TEMPDATES SET T07_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T07_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T07_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T08_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T08_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T08_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T09_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T09_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T09_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T10_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T10_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T10_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T11_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T11_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T11_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T12_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T12_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T12_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T13_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T13_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T13_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T14_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T14_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T14_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T15_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T15_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T15_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T16_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T16_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T16_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T17_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T17_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T17_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T18_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T18_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T18_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T19_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T19_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T19_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)

	UPDATE #TEMPDATES SET T20_START = (SELECT MIN(ELGB_START_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	UPDATE #TEMPDATES SET T20_END = (SELECT MIN(ELGB_END_DT) FROM #TEMP1 T 
		WHERE #TEMPDATES.AGLTY_INDIV_ID = T.AGLTY_INDIV_ID)
	DELETE FROM #TEMP1 
		WHERE ELGB_START_DT IN (SELECT T20_START FROM #TEMPDATES 
		WHERE #TEMP1.AGLTY_INDIV_ID = #TEMPDATES.AGLTY_INDIV_ID)


CREATE TABLE #TENURE (AGLTY_INDIV_ID NVARCHAR(20), 
L1 INT,
L2 INT,
L3 INT,
L4 INT,
L5 INT,
L6 INT,
L7 INT,
L8 INT,
L9 INT,
L10 INT,
L11 INT,
L12 INT,
L13 INT,
L14 INT,
L15 INT,
L16 INT,
L17 INT,
L18 INT,
L19 INT,
L20 INT,
)
INSERT INTO #TENURE
SELECT AGLTY_INDIV_ID, 
(SELECT CASE 
WHEN T01_END > T02_START THEN DATEDIFF(DAY,T01_START,T02_START)
ELSE DATEDIFF(DAY,T01_START,T01_END) 
END) AS L1,
(SELECT CASE 
WHEN T02_END < T03_START OR T03_START IS NULL THEN DATEDIFF(DAY,T02_START,T02_END) 
WHEN T02_END > T03_START AND T03_START IS NOT NULL THEN DATEDIFF(DAY,T02_START,T03_START)
END) AS L2,
(SELECT CASE 
WHEN T03_END < T04_START OR T04_START IS NULL THEN DATEDIFF(DAY,T03_START,T03_END) 
WHEN T03_END > T04_START AND T04_START IS NOT NULL THEN DATEDIFF(DAY,T03_START,T04_START)
END) AS L3,
(SELECT CASE 
WHEN T04_END < T05_START OR T05_START IS NULL THEN DATEDIFF(DAY,T04_START,T04_END) 
WHEN T04_END > T05_START AND T05_START IS NOT NULL THEN DATEDIFF(DAY,T04_START,T05_START)
END) AS L4,
(SELECT CASE 
WHEN T05_END < T06_START OR T06_START IS NULL THEN DATEDIFF(DAY,T05_START,T05_END) 
WHEN T05_END > T06_START AND T06_START IS NOT NULL THEN DATEDIFF(DAY,T05_START,T06_START)
END) AS L5,
(SELECT CASE 
WHEN T06_END < T07_START OR T07_START IS NULL THEN DATEDIFF(DAY,T06_START,T06_END) 
WHEN T06_END > T07_START AND T07_START IS NOT NULL THEN DATEDIFF(DAY,T06_START,T07_START)
END) AS L6,
(SELECT CASE 
WHEN T07_END < T08_START OR T08_START IS NULL THEN DATEDIFF(DAY,T07_START,T07_END) 
WHEN T07_END > T08_START AND T08_START IS NOT NULL THEN DATEDIFF(DAY,T07_START,T08_START)
END) AS L7,
(SELECT CASE 
WHEN T08_END < T09_START OR T09_START IS NULL THEN DATEDIFF(DAY,T08_START,T08_END) 
WHEN T08_END > T09_START AND T09_START IS NOT NULL THEN DATEDIFF(DAY,T08_START,T09_START)
END) AS L8,
(SELECT CASE 
WHEN T09_END < T10_START OR T10_START IS NULL THEN DATEDIFF(DAY,T09_START,T09_END) 
WHEN T09_END > T10_START AND T10_START IS NOT NULL THEN DATEDIFF(DAY,T09_START,T10_START)
END) AS L9,
(SELECT CASE 
WHEN T10_END < T11_START OR T11_START IS NULL THEN DATEDIFF(DAY,T10_START,T10_END) 
WHEN T10_END > T11_START AND T11_START IS NOT NULL THEN DATEDIFF(DAY,T10_START,T11_START)
END) AS L10,
(SELECT CASE 
WHEN T11_END < T12_START OR T12_START IS NULL THEN DATEDIFF(DAY,T11_START,T11_END) 
WHEN T11_END > T12_START AND T12_START IS NOT NULL THEN DATEDIFF(DAY,T11_START,T12_START)
END) AS L11,
(SELECT CASE 
WHEN T12_END < T13_START OR T13_START IS NULL THEN DATEDIFF(DAY,T12_START,T12_END) 
WHEN T12_END > T13_START AND T13_START IS NOT NULL THEN DATEDIFF(DAY,T12_START,T13_START)
END) AS L12,
(SELECT CASE 
WHEN T13_END < T14_START OR T14_START IS NULL THEN DATEDIFF(DAY,T13_START,T13_END) 
WHEN T13_END > T14_START AND T14_START IS NOT NULL THEN DATEDIFF(DAY,T13_START,T14_START)
END) AS L13,
(SELECT CASE 
WHEN T14_END < T15_START OR T15_START IS NULL THEN DATEDIFF(DAY,T14_START,T14_END) 
WHEN T14_END > T15_START AND T15_START IS NOT NULL THEN DATEDIFF(DAY,T14_START,T15_START)
END) AS L14,
(SELECT CASE 
WHEN T15_END < T16_START OR T16_START IS NULL THEN DATEDIFF(DAY,T15_START,T15_END) 
WHEN T15_END > T16_START AND T16_START IS NOT NULL THEN DATEDIFF(DAY,T15_START,T16_START)
END) AS L15,
(SELECT CASE 
WHEN T16_END < T17_START OR T17_START IS NULL THEN DATEDIFF(DAY,T16_START,T16_END) 
WHEN T16_END > T17_START AND T17_START IS NOT NULL THEN DATEDIFF(DAY,T16_START,T17_START)
END) AS L16,
(SELECT CASE 
WHEN T17_END < T18_START OR T18_START IS NULL THEN DATEDIFF(DAY,T17_START,T17_END) 
WHEN T17_END > T18_START AND T18_START IS NOT NULL THEN DATEDIFF(DAY,T17_START,T18_START)
END) AS L17,
(SELECT CASE 
WHEN T18_END < T19_START OR T19_START IS NULL THEN DATEDIFF(DAY,T18_START,T18_END) 
WHEN T18_END > T19_START AND T19_START IS NOT NULL THEN DATEDIFF(DAY,T18_START,T19_START)
END) AS L18,
(SELECT CASE 
WHEN T19_END < T20_START OR T20_START IS NULL THEN DATEDIFF(DAY,T19_START,T19_END) 
WHEN T19_END > T20_START AND T20_START IS NOT NULL THEN DATEDIFF(DAY,T19_START,T20_START)
END) AS L19,
DATEDIFF(DAY,T20_START,T20_END) AS L20
FROM #TEMPDATES


CREATE TABLE #SUM (AGLTY_INDIV_ID NVARCHAR(20), MONTHS INT)
INSERT #SUM SELECT AGLTY_INDIV_ID, L1 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L2 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L3 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L4 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L5 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L6 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L7 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L8 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L9 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L10 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L11 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L12 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L13 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L14 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L15 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L16 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L17 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L18 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L19 FROM #TENURE
INSERT #SUM SELECT AGLTY_INDIV_ID, L20 FROM #TENURE



SELECT  AGLTY_INDIV_ID, 
		SUM(MONTHS)/365.242 AS TENURE_YEARS, --TENURE IN YEARS (USING AVG OF 365.242 DAYS)
		SUM(MONTHS)/30 AS TENURE_MONTHS, -- TENURE IN MONTHS (USING AVG OF 30 DAYS)
		SUM(MONTHS) AS TENURE_DAYS --TENURE IN DAYS
INTO WS_EHAYNES.dbo.KPIF_EM_22_Targeting_Tenure_OE20 --FILE OUTPUT
FROM #SUM 
GROUP BY AGLTY_INDIV_ID

SELECT TOP 100 * FROM #SUM

DROP TABLE #DATA
DROP TABLE #TEMP1
DROP TABLE #TENURE
DROP TABLE #SUM
DROP TABLE #TEMPDATES
SELECT TOP 100 * FROM WS_EHAYNES.dbo.KPIF_EM_22_Targeting_Tenure_OE20 --SELECT FILE FOR VIEWING